name: coinbase_exchange
description: A library for the coinbase cloud exchange
version: 0.0.1
repository: https://github.com/pcrady/coinbase_exchange

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  http: ^0.13.4
  json_serializable: ^4.1.3
  json_annotation: ^4.1.0
  web_socket_channel: ^2.1.0
  logger: ^1.0.0
  tuple: ^2.0.0
  crypto: ^3.0.1

dev_dependencies:
  build_runner: ^2.0.4
  test: ^1.17.5


