name: coinbase_exchange
description: An unoffical coinbase exchange sdk to get real
  time pricing data and historical pricing data. The sdk also
  allows users to make trades on the coinbase platform.

version: 2.0.8
repository: https://github.com/pcrady/coinbase_exchange

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  http: ^0.13.4
  json_serializable: ^6.0.1
  json_annotation: ^4.3.0
  web_socket_channel: ^2.1.0
  tuple: ^2.0.0
  crypto: ^3.0.1
  logger: ^1.1.0

dev_dependencies:
  build_runner: ^2.0.4
  test: ^1.17.5


