name: coinbase_dart
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.3
  json_serializable: ^4.1.3
  web_socket_channel: ^2.1.0
  logger: ^1.0.0
  tuple: ^2.0.0

dev_dependencies:
  build_runner: ^2.0.4
  test: ^1.17.5


